# Generated by Django 5.2.7 on 2025-11-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='productos_chat',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('B', 'Borrador'), ('P', 'Pendiente'), ('R', 'Realizado')], default='P', max_length=20),
        ),
    ]
