# Generated by Django 5.2.7 on 2025-11-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedido_productos_chat_alter_pedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('B', 'Borrador'), ('P', 'Pendiente'), ('R', 'Realizado'), ('C', 'Cancelado')], default='P', max_length=20),
        ),
    ]
