# Generated by Django 5.2.7 on 2025-11-26 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_alter_pedido_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='productos_chat',
        ),
    ]
