# Generated by Django 5.2.7 on 2025-11-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_alter_pedido_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionChatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Configuración Principal', max_length=100)),
                ('instrucciones_sistema', models.TextField(blank=True, default='', help_text="Añade aquí reglas personalizadas para el prompt del sistema. Ejemplo: 'Si preguntan por envíos, di que son gratis a partir de 50€'.")),
                ('activado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuración del Chatbot (Pedidos)',
                'verbose_name_plural': 'Configuración del Chatbot (Pedidos)',
            },
        ),
    ]
