# Generated by Django 5.2.7 on 2025-11-27 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_configuracionchatbot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='productos_chat',
        ),
    ]
