# Generated by Django 5.2.7 on 2025-11-15 18:02

from django.db import migrations
from django.contrib.auth.hashers import make_password

def crear_usuarios_iniciales(apps, schema_editor):

    User = apps.get_model('usuarios', 'CustomUser')
    db_alias = schema_editor.connection.alias

    hashed_password_admin = make_password('admin12345')
    admin_user = User(
        email='admin@ejemplo.com',
        nombre='admin',
        password=hashed_password_admin,
        is_staff=True,
        is_superuser=True,
        is_active=True 
    )
    admin_user.save(using=db_alias)


    hashed_password_cliente = make_password('test12345')

    cliente1 = User(
        email='cliente1@ejemplo.com',
        nombre='cliente1',
        telefono='123456789',
        password=hashed_password_cliente,
        is_staff=False,
        is_superuser=False,
        is_active=True
    )
    cliente1.save(using=db_alias)

    cliente2 = User(
        email='cliente2@ejemplo.com',
        nombre='cliente2',
        telefono='987654321',
        password=hashed_password_cliente,
        is_staff=False,
        is_superuser=False,
        is_active=True
    )
    cliente2.save(using=db_alias)


def revertir_usuarios_iniciales(apps, schema_editor):
    """
    Elimina los usuarios creados si se revierte la migración.
    """
    User = apps.get_model('usuarios', 'CustomUser')
    db_alias = schema_editor.connection.alias
    
    User.objects.using(db_alias).filter(
        email__in=[
            'admin@ejemplo.com',
            'cliente1@ejemplo.com',
            'cliente2@ejemplo.com'
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            crear_usuarios_iniciales, 
            reverse_code=revertir_usuarios_iniciales
        ),
    ]