# Generated by Django 5.2.7 on 2025-11-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuarios_iniciales'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='historial_productos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
