# Generated by Django 5.2.7 on 2025-11-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_customuser_historial_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_vip',
            field=models.BooleanField(default=False, verbose_name='Cliente Habitual'),
        ),
    ]
