# Generated by Django 5.2.7 on 2025-11-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='tipo',
            field=models.CharField(max_length=100),
        ),
    ]
