# Generated by Django 5.2.7 on 2025-11-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_remove_cita_tipo_cita_observaciones_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionChatbotCitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Configuración Citas', max_length=100)),
                ('instrucciones_adicionales', models.TextField(blank=True, default='', help_text="Reglas extra para el recepcionista. Ej: 'Recuerda que los viernes cerramos a las 14:00 excepcionalmente'.")),
            ],
            options={
                'verbose_name': 'Configuración del Chatbot (Citas)',
                'verbose_name_plural': 'Configuración del Chatbot (Citas)',
            },
        ),
    ]
