# Generated by Django 5.2.7 on 2025-11-15 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_producto_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='enlace_img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
